
#ifndef VERY_SIMPLE_FILE_SYSTEM_ERRORS_H
#define VERY_SIMPLE_FILE_SYSTEM_ERRORS_H

#define DISK_OPEN_ERROR -1
#define SUPER_BLOCK_ERROR -2
#define FILE_OPEN_ERROR -3
#define NOT_UNIQUE_FILE_NAME -4
#define NOT_ENOUGH_SPACE -5
#define NEW_INODE_CREATION_ERROR -6
#define CANNOT_FIND_FILE -7
#endif //VERY_SIMPLE_FILE_SYSTEM_ERRORS_H
